name: "Action 01 - Processamento de Entrada"

on:
  push:
    branches:
      - main
    paths:
      - 'entrada/**'

jobs:
  generate-output:
    name: generate-output
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create directories
        run: |
          mkdir -p entrada output template_atualizado template_final

      - name: Process input files
        shell: bash
        run: |
          shopt -s nocaseglob
          
          for file in entrada/*.yaml; do
            # Verifica se o arquivo existe para evitar erro caso a pasta esteja vazia
            [ -e "$file" ] || continue
            
            # Ignora arquivos que já são templates
            if [[ ! "$file" =~ _TEMPLATE\.yaml$ ]]; then
              filename=$(basename "$file" .yaml)
              template_file="entrada/${filename}_TEMPLATE.yaml"
              output_file="output/${filename}_TEMPLATE_GERADO.yaml"
              
              if [ -f "$template_file" ]; then
                echo "Processando: $file com template $template_file"
                python compare.py -f1 "$template_file" -f2 "$file" -o "$output_file"
                
                if [ -f "vars.txt" ]; then
                  mv vars.txt output/
                fi
              fi
            fi
          done

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add output/
          
          # Verifica se há mudanças antes de prosseguir
          if ! git diff --cached --quiet; then
            git commit -m "action 01: templates gerados em output [skip ci]"
            git push
          else
            echo "Nenhuma alteração detectada no output."
          fi
